CLASS Z_CLASS_ DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  interfaces if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS Z_CLASS_ IMPLEMENTATION.
METHOD IF_OO_ADT_CLASSRUN~MAIN.
out->write( 'Hello World!' ).
ENDMETHOD.
ENDCLASS.
